version: "3.9"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  triton:
    image: nvcr.io/nvidia/tritonserver:23.06-py3
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./model_repository:/models
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: tritonserver --model-repository=/models

  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - triton
    environment:
      - MONGO_URI=mongodb://mongo:27017

volumes:
  mongo_data:
